services:
  grading-server-app-1:
    container_name: grading-server-app-1
    build: .
    ports:
      - "18081:8080"
    image: lmw7414/grading-server-app
    restart: always
    deploy:
      resources:
        limits:
          memory: '512m'